name: tassie.online
favicon: null
layout_spectrum: 0.24314
typography_spectrum: 0.16048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59862159-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
