typography_spectrum: 0.16048
color:
  brandColors:
    - '#000100'
    - '#fdfdfd'
    - '#403927'
    - '#dad0d9'
    - '#93888e'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37926
analytics:
  google: UA-59862159-8
  facebook: null
  twitter: null
author:
  url: ''
name: tassie.online
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
